language: node_js
node_js: '0.10'
deploy:
  provider: nodejitsu
  user: chrismatheson
  api_key:
    secure: hTzK984J808C0Hz29HrQTGuykFDBeAscqvYo+HI+yO6v7AiMK9l8iBdHHgK2Oz19ZX5py/fd2+BYBUTQ4zLTl+S2w3S6L+588ABDKyhf9J3n1yYOKb1eog5JsIorbusxG9B+f2xWPnyj23wdXVKEN+KFt2tEMu2UU1KCata1LDM=
  on:
    repo: peachproductions/modelbuilder
    branch:
      - uk
      - us
notifications:
  email: false
