language: node_js
node_js:
- '0.11'
script: echo do tests
deploy:
  - provider: s3
    endpoint: static.unitsofsound.com.s3-website-eu-west-1.amazonaws.com
    region: eu-west-1
    access_key_id: AKIAJOK42BNIW3ABVB3A
    secret_access_key:
      secure: JyHBwZn4Alk5JkKrQ82tJDV6LoRhX7WUOz5Gy9XtAfcggnQ6WEn6jiZMfb3F3PEDk+TKdjb16/4xiMZqUACN2zr+peX00BnCAprfS1z4TG6AyT2JuynTuwEl1WcRS9xQYiP0ONdq0MkLZFIrU3d0TUR754Nj/N0gvgDOH6eM7uA=
    bucket: static.unitsofsound.com
    skip_cleanup: true
    upload-dir: modelbuilder-uk
    on:
      branch: uk
  - provider: s3
    endpoint: static.unitsofsound.com.s3-website-eu-west-1.amazonaws.com
    region: eu-west-1
    access_key_id: AKIAJOK42BNIW3ABVB3A
    secret_access_key:
      secure: JyHBwZn4Alk5JkKrQ82tJDV6LoRhX7WUOz5Gy9XtAfcggnQ6WEn6jiZMfb3F3PEDk+TKdjb16/4xiMZqUACN2zr+peX00BnCAprfS1z4TG6AyT2JuynTuwEl1WcRS9xQYiP0ONdq0MkLZFIrU3d0TUR754Nj/N0gvgDOH6eM7uA=
    bucket: static.unitsofsound.com
    skip_cleanup: true
    upload-dir: modelbuilder-us
    on:
      branch: us
notifications:
  email: false
