language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  - provider: s3
    endpoint: static.unitsofsound.com.s3-website-eu-west-1.amazonaws.com
    region: eu-west-1
    access_key_id: AKIAJOK42BNIW3ABVB3A
    secret_access_key:
      secure: "i5y1t1MkCarVc594UX5e8AshdqKVWOyADfLI6X/p9cNlS4i5URCwVF0tHQKvVKyJ1fYiwyuN/Smv9nFowwbJOwJevgW7WJp3j5wsLGsLeqzhYBCforIlcdTYZrU8mvocStxi/czIYFR/N/TprG3hcQqbKbX7w2L/83POj7nOsEc="
    bucket: "static.unitsofsound.com"
    skip_cleanup: true
    upload-dir: modelbuilder-uk
    on:
      branch: uk
  - provider: s3
    endpoint: static.unitsofsound.com.s3-website-eu-west-1.amazonaws.com
    region: eu-west-1
    access_key_id: AKIAJOK42BNIW3ABVB3A
    secret_access_key:
      secure: "i5y1t1MkCarVc594UX5e8AshdqKVWOyADfLI6X/p9cNlS4i5URCwVF0tHQKvVKyJ1fYiwyuN/Smv9nFowwbJOwJevgW7WJp3j5wsLGsLeqzhYBCforIlcdTYZrU8mvocStxi/czIYFR/N/TprG3hcQqbKbX7w2L/83POj7nOsEc="
    bucket: "static.unitsofsound.com"
    skip_cleanup: true
    upload-dir: modelbuilder-us
    on:
      branch: us
notifications:
  email: false